local TrajetPL = {
    { map = "83887104", path = "396",},
    { map = "-3,-14", path = "top", fight = true },
    { map = "-3,-16", path = "top", fight = true },
    { map = "-3,-18", path = "top", fight = true },
    { map = "-2,-19", path = "top", fight = true },
    { map = "-3,-20", path = "top", fight = true },
    { map = "-2,-14", path = "left", fight = true },
    { map = "-2,-15", path = "top", fight = true },
    { map = "-2,-17", path = "top", fight = true },
    { map = "-2,-16", path = "left", fight = true },
    { map = "-2,-18", path = "left", fight = true },
    { map = "-2,-20", path = "left", fight = true },
    { map = "-3,-15", path = "right", fight = true },
    { map = "-3,-17", path = "right", fight = true },
    { map = "-3,-19", path = "right", fight = true },
    { map = "-3,-21", path = "right" },
    { map = "-2,-21", path = "top", fight = true },
    { map = "-2,-22", path = "right", fight = true },
    { map = "-1,-22", path = "top", fight = true },
    { map = "-1,-23", path = "right", fight = true },
    { map = "0,-23", path = "right", fight = true },
    { map = "1,-23", path = "right", fight = true },
    { map = "2,-23", path = "right", fight = true },
    { map = "3,-23", path = "right", fight = true },
    { map = "4,-23", path = "right", fight = true },
    { map = "6,-22", path = "right", fight = true },
    { map = "5,-23", path = "right", fight = true },
    { map = "7,-22", path = "right", fight = true },
    { map = "8,-22", path = "bottom", fight = true },
    { map = "8,-21", path = "bottom", fight = true },
    { map = "8,-20", path = "bottom", fight = true },
    { map = "8,-19", path = "bottom", fight = true },
    { map = "8,-18", path = "bottom", fight = true },
    { map = "8,-16", path = "bottom", fight = true },
    { map = "8,-17", path = "bottom", fight = true },
    { map = "8,-15", path = "bottom", fight = true },
    { map = "8,-14", path = "left", fight = true },
    { map = "7,-14", path = "left", fight = true },
    { map = "6,-14", path = "left", fight = true },
    { map = "5,-14", path = "left", fight = true },
    { map = "4,-13", path = "left", fight = true },
    { map = "2,-13", path = "left", fight = true },
    { map = "3,-13", path = "left", fight = true },
    { map = "1,-13", path = "left", fight = true },
    { map = "0,-13", path = "left", fight = true },
    { map = "-1,-13", path = "left", fight = true },
    { map = "-2,-13", path = "left", fight = true },
    { map = "-3,-13", path = "top", fight = true },
    { map = "4,-14", path = "bottom" },
    { map = "6,-23", path = "bottom" },  

    { map = "7,-15", path = "left" },
    { map = "7,-16", path = "left" },
    { map = "7,-18", path = "left" },
    { map = "7,-19", path = "left" },
    { map = "7,-20", path = "left" },
    { map = "7,-21", path = "left" },
    { map = "6,-21", path = "left" },
    { map = "6,-20", path = "left" },
    { map = "6,-19", path = "left" },
    { map = "6,-18", path = "left" },
    { map = "6,-17", path = "left" },
    { map = "6,-16", path = "left" },
    { map = "6,-15", path = "left" },
    { map = "84674566", path = "left" },
    { map = "5,-15", path = "left" },
    { map = "5,-16", path = "left" },
    { map = "5,-17", path = "left" },
    { map = "5,-18", path = "left" },
    { map = "5,-19", path = "left" },
    { map = "5,-20", path = "left" },
    { map = "5,-22", path = "left" },
    { map = "4,-22", path = "left" },
    { map = "4,-20", path = "left" },
    { map = "4,-18", path = "left" },
    { map = "4,-17", path = "left" },
    { map = "4,-19", path = "left" },
    { map = "4,-15", path = "left" },
    { map = "3,-14", path = "left" },
    { map = "3,-15", path = "left" },
    { map = "3,-16", path = "left" },
    { map = "3,-17", path = "left" },
    { map = "3,-18", path = "left" },
    { map = "3,-19", path = "left" },
    { map = "3,-20", path = "left" },
    { map = "3,-21", path = "left" },
    { map = "3,-22", path = "left" },
    { map = "4,-21", path = "left" },
    { map = "5,-21", path = "left" },
    { map = "2,-22", path = "left" },
    { map = "2,-21", path = "left" },
    { map = "2,-20", path = "left" },
    { map = "2,-19", path = "left" },
    { map = "2,-18", path = "left" },
    { map = "2,-17", path = "left" },
    { map = "2,-15", path = "left" },
    { map = "2,-14", path = "left" },
    { map = "2,-16", path = "left" },
    { map = "1,-15", path = "left" },
    { map = "1,-14", path = "left" },
    { map = "0,-14", path = "left" },
    { map = "0,-15", path = "left" },
    { map = "1,-16", path = "left" },
    { map = "0,-17", path = "left" },
    { map = "0,-16", path = "left" },
    { map = "-1,-14", path = "left" },
    { map = "1,-17", path = "left" },
    { map = "1,-18", path = "left" },
    { map = "0,-18", path = "left" },
    { map = "0,-19", path = "left" },
    { map = "1,-19", path = "left" },
    { map = "1,-20", path = "left" },
    { map = "0,-20", path = "left" },
    { map = "0,-21", path = "left" },
    { map = "1,-21", path = "left" },
    { map = "0,-22", path = "left" },
    { map = "-1,-20", path = "left" },
    { map = "-1,-21", path = "bottom" },
    { map = "-1,-15", path = "bottom" },
    { map = "-1,-16", path = "bottom" },
    { map = "-1,-17", path = "top" },
    { map = "-1,-19", path = "top" },
    { map = "7,-17", path = "left" },
}

local TrajetBouftou = {
    { map = "1,-21", path = "right" },
    { map = "2,-21", path = "right" },
    { map = "3,-21", path = "right" },
    { map = "4,-21", path = "bottom" },
    { map = "4,-20", path = "bottom" },
    { map = "4,-19", path = "bottom" },
    { map = "4,-18", path = "bottom" },
    { map = "4,-17", path = "bottom" },
    { map = "4,-16", path = "bottom" },
    { map = "4,-15", path = "bottom(557)" },
    { map = "4,-14", path = "bottom" },
    { map = "4,-13", path = "bottom" },
    { map = "4,-12", path = "bottom" },
    { map = "4,-11", path = "bottom" },
    { map = "4,-10", path = "left" },
    { map = "3,-10", path = "left" },
    { map = "2,-10", path = "bottom" },
    { map = "2,-9", path = "bottom" },
    { map = "2,-8", path = "left" },
    { map = "1,-8", path = "bottom(444)" },
    { map = "1,-7", path = "bottom" },
    { map = "1,-6", path = "bottom" },
    { map = "1,-5", path = "bottom" },
    { map = "1,-4", path = "bottom" },
    { map = "1,-3", path = "bottom" },
    { map = "1,-2", path = "left" },
    { map = "0,-2", path = "left" },
    { map = "-1,-2", path = "left" },
    { map = "-2,-2", path = "bottom" },
    { map = "-2,-1", path = "bottom" },
    { map = "-2,0", custom = function()
        map:changeMap("right")
    end},

    { map = "-1,0", path = "right" },

    { map = "0,0", path = "right" },
    { map = "1,0", path = "right" },
    { map = "2,0", path = "right" },
    { map = "3,0", path = "right" },
    { map = "4,0", path = "right" },
    { map = "5,1", path = "bottom" },
    { map = "5,0", path = "bottom" },
    { map = "5,2", path = "bottom" },
    { map = "5,3", path = "bottom" },
    { map = "5,5", path = "bottom" },
    { map = "5,4", path = "bottom" },
    { map = "5,6", path = "bottom" },
    { map = "5,7", custom = function()
        map:changeMap("right")
    end},
    { map = "-3,-18", path = "right" },
    { map = "-3,-17", path = "right" },
    { map = "-3,-16", path = "right" },
    { map = "-3,-15", path = "right" },
    { map = "-3,-14", path = "right" },
    { map = "-3,-13", path = "right" },
    { map = "-2,-13", path = "right" },
    { map = "-2,-14", path = "right" },
    { map = "-2,-18", path = "right" },
    { map = "-1,-13", path = "right" },
    { map = "0,-13", path = "right" },
    { map = "1,-13", path = "right" },
    { map = "2,-13", path = "right" },
    { map = "3,-13", path = "right" },
    { map = "0,-14", path = "right" },
    { map = "-1,-14", path = "right" },
    { map = "1,-14", path = "right" },
    { map = "2,-14", path = "right" },
    { map = "3,-14", path = "right" },
    { map = "0,-22", path = "bottom" },
    { map = "1,-22", path = "bottom" },
    { map = "2,-22", path = "bottom" },
    { map = "3,-22", path = "bottom" },
    { map = "4,-22", path = "bottom" },
    { map = "5,-22", path = "bottom" },
    { map = "5,-21", path = "bottom" },
    { map = "6,-21", path = "bottom" },
    { map = "7,-21", path = "bottom" },
    { map = "7,-20", path = "bottom" },
    { map = "6,-20", path = "bottom" },
    { map = "5,-20", path = "bottom" },
    { map = "4,-20", path = "bottom" },
    { map = "4,-21", path = "bottom" },
    { map = "3,-21", path = "bottom" },
    { map = "3,-20", path = "bottom" },
    { map = "2,-21", path = "bottom" },
    { map = "1,-21", path = "bottom" },
    { map = "0,-21", path = "bottom" },
    { map = "-1,-21", path = "bottom" },
    { map = "-1,-20", path = "bottom" },
    { map = "0,-20", path = "bottom" },
    { map = "1,-20", path = "bottom" },
    { map = "2,-20", path = "bottom" },
    { map = "-2,-22", path = "bottom" },
    { map = "-3,-22", path = "bottom" },
    { map = "-2,-21", path = "bottom" },
    { map = "-3,-21", path = "bottom" },
    { map = "-3,-19", path = "right" },
    { map = "-3,-20", path = "right" },
    { map = "-2,-20", path = "right" },
    { map = "-1,-19", path = "right" },
    { map = "0,-19", path = "right" },
    { map = "1,-19", path = "right" },
    { map = "2,-19", path = "right" },
    { map = "3,-19", path = "right" },
    { map = "5,-19", path = "left" },
    { map = "6,-19", path = "left" },
    { map = "7,-19", path = "left" },
    { map = "7,-18", path = "left" },
    { map = "7,-17", path = "left" },
    { map = "7,-16", path = "left" },
    { map = "7,-15", path = "left" },
    { map = "6,-15", path = "left" },
    { map = "6,-16", path = "left" },
    { map = "6,-17", path = "left" },
    { map = "6,-18", path = "left" },
    { map = "5,-18", path = "left" },
    { map = "5,-17", path = "left" },
    { map = "5,-16", path = "left" },
    { map = "5,-15", path = "left" },
    { map = "3,-18", path = "right" },
    { map = "3,-17", path = "right" },
    { map = "3,-16", path = "right" },
    { map = "3,-15", path = "right" },
    { map = "2,-15", path = "right" },
    { map = "2,-16", path = "right" },
    { map = "2,-17", path = "right" },
    { map = "2,-18", path = "right" },
    { map = "1,-18", path = "right" },
    { map = "1,-17", path = "right" },
    { map = "1,-16", path = "right" },
    { map = "1,-15", path = "right" },
    { map = "0,-15", path = "right" },
    { map = "0,-16", path = "right" },
    { map = "0,-17", path = "right" },
    { map = "0,-18", path = "right" },
    { map = "-1,-18", path = "right" },
    { map = "-1,-17", path = "right" },
    { map = "-1,-15", path = "right" },
    { map = "-1,-16", path = "right" },
    { map = "-1,-23", path = "right" },
    { map = "1,-23", path = "right" },
    { map = "0,-23", path = "right" },
    { map = "2,-23", path = "right" },
    { map = "3,-23", path = "right" },
    { map = "4,-23", path = "right" },
    { map = "5,-23", path = "bottom" },
    { map = "-2,-15", path = "top" },
    { map = "-2,-16", path = "top" },
    { map = "-2,-17", path = "top" },
    { map = "-2,-23", path = "bottom" },
    { map = "-2,-19", path = "top" },
    { map = "8,-20", path = "bottom" },
    { map = "8,-21", path = "bottom" },
    { map = "8,-19", path = "bottom" },
    { map = "8,-18", path = "bottom" },
    { map = "8,-17", path = "bottom" },
    { map = "8,-16", path = "bottom" },
    { map = "8,-15", path = "bottom" },
    { map = "8,-14", path = "left" },
    { map = "7,-14", path = "left" },
    { map = "6,-14", path = "left" },
    { map = "5,-14", path = "left" },
    { map = "5,-13", path = "left" },
    { map = "6,-13", path = "left" },
    { map = "7,-13", path = "left" },
    { map = "8,-13", path = "left" },
    { map = "8,-22", path = "left" },
    { map = "7,-22", path = "left" },
    { map = "6,-22", path = "left" },

    { map = "10,22", path = "zaap(88082704)" },
    {map = "5,7", custom = function() map:useById(472656, -2) map:changeMap("bottom") end},
    {map = "5,8", path = "bottom|left", fight = true},
    {map = "4,8", path = "bottom|left", fight = true},
    {map = "3,8", path = "bottom|left", fight = true},
    {map = "2,8", path = "bottom|left", fight = true},
    {map = "7,10", path = "left", fight = true},
    {map = "6,10", path = "top|bottom|left|right", fight = true},
    {map = "4,10", path = "top|bottom|left|right", fight = true},
    {map = "5,10", path = "top|bottom|left|right", fight = true},
    {map = "3,10", path = "top|bottom|left|right", fight = true},
    {map = "2,10", path = "top|bottom|left|right", fight = true},
    {map = "2,12", path = "left", fight = true},
    {map = "1,12", path = "left", fight = true},
    {map = "0,12", path = "top|right", fight = true},
    {map = "0,11", path = "top|right", fight = true},
    {map = "0,10", path = "top|right", fight = true},
    {map = "0,9", path = "top|right", fight = true},
    {map = "0,8", path = "top|right", fight = true},
    {map = "0,7", path = "right", fight = true},
    {map = "1,7", path = "bottom"},
    {map = "1,8", path = "bottom", fight = true},
    {map = "1,10", path = "top|bottom|left|right", fight = true},
    {map = "1,11", path = "top|bottom|left|right", fight = true},
    {map = "2,9", path = "top|bottom|left|right", fight = true},
    {map = "3,9", path = "top|bottom|left|right", fight = true},
    {map = "4,9", path = "top|bottom|left|right", fight = true},
    {map = "5,9", path = "top|bottom|left|right", fight = true},
    {map = "6,9", path = "top|bottom|left|right", fight = true},
    {map = "7,9", path = "bottom"},
    {map = "2,11", path = "top|bottom|left|right", fight = true},
    {map = "3,11", path = "top|bottom|left|right", fight = true},
    {map = "4,11", path = "top|bottom|left|right", fight = true},
    {map = "5,11", path = "top|bottom|left|right", fight = true},
    {map = "6,11", path = "top|bottom|left|right", fight = true},
    {map = "7,11", path = "bottom", fight = true},
    {map = "7,12", path = "left"},
    {map = "6,12", path = "left"},
    {map = "5,12", path = "left"},
    {map = "4,12", path = "left"},
    {map = "3,12", path = "left"},
    {map = "6,8", path = "bottom|left", fight = true},
    {map = "1,9", path = "top|bottom|left|right", fight = true},
}



local function PopoRappel()
    if inventory:itemCount(548) == 0 then
        npc:npcBuy()
        global:delay(500)
        sale:buyItem(548, 1, 1000)

        if inventory:itemCount(548) == 0 then
            sale:buyItem(548, 10, 10000)
        end
        global:delay(500)
        global:leaveDialog()
        global:delay(500)
    end
    inventory:useItem(548)
end

local function treatMaps(maps)
    for _, element in ipairs(maps) do
        local condition = map:onMap(element.map) 

        if condition then
            return maps
        end
    end

	if not map:onMap(maps[1].map) then
		local toward = maps[1].map:split(",")
		if #toward == 2 then
			map:moveToward(tonumber(toward[1]), tonumber(toward[2]))
		elseif #toward == 1 then
			map:moveToward(tonumber(maps[1].map))
		end
	end
end


function move()
    if character:level() < 43 then
        return treatMaps(TrajetPL)
    else
        return treatMaps(TrajetBouftou)
    end
end


function bank()
    inventory:openBank()
    exchange:putAllItems()
    global:leaveDialog()
    return move()
end



function phenix()
    return {
        { map = "-3,-11", path = "right" },
        { map = "-2,-11", path = "right" },
        { map = "-1,-11", path = "right" },
        { map = "1,-11", path = "right" },
        { map = "0,-11", path = "right" },
        { map = "2,-11", path = "top" },
        { map = "2,-12", custom = function() map:door(272) map:changeMap("top") end},

        {map = "9,16", path = "right"},
		{map = "10,16", path = "right"},
		{map = "11,16", path = "right"},
		{map = "12,16", path = "right"},
		{map = "13,16", path = "top"},
		{map = "13,15", path = "top"},
		{map = "13,14", path = "top"},
		{map = "13,13", path = "top"},
		{map = "13,12", path = "left"},
		{map = "12,12", custom = function() map:door(184) PopoRappel() end},
    }
end